### ISSUE TITLE
main 已经在CMakeCCompilerld.obj中定义

### ISSUE THREAD

**Issue by yiliacheng** [astrand130/Weekend-Raytracer#1]

**Comment by ying-cy** [comment]
> 当我在VS2019的编译器里尝试运行的时候，会报这个错，不知道如何解决，请指教。
> main已经在CMakeCCompilerld.obj中定义

**Comment by KenzieMac130** [comment]
Please only report issues with details. I assume this has been resolved given that you closed this yourself.
